app = "songgen-studio"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[env]
  GRADIO_SERVER_NAME = "0.0.0.0"
  GRADIO_SERVER_PORT = "7860"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 8
  gpu_kind = "a10"
